In [2]:
import pandas as pd
import numpy as np
import re
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
empl_roll = pd.DataFrame(pd.read_csv('CR Indexed Worker Roster - Sales 2021-01-04 19_16 CST.xlsx - Sheet1.csv'))
user_df = pd.DataFrame(pd.read_csv('ihm_users.csv'))
market_owners = pd.DataFrame(pd.read_csv('ihm_account_management.csv'))
workday = pd.DataFrame(pd.read_csv('usersChanges_2021_02_15_11_54.csv'))
revenue = pd.DataFrame(pd.read_csv('sf_duplicates.csv'))
projects = pd.DataFrame(pd.read_csv('iheart_projects.csv'))
newhr = pd.DataFrame(pd.read_csv('March iHeart Everyone HR Pull.xlsx - Sheet1.csv'))

In [4]:
# empl_roll[empl_roll.apply(lambda row: row.astype(str).str.contains('Kristen C Delaney', case=False).any(), axis=1)]

In [10]:
newhr[newhr.apply(lambda row: row.astype(str).str.contains('Sean Johnson', case=False).any(), axis=1)]

,First Name,Last Name,Name,User - Division Parent,User - Division,User - Position,User - User Email,User - Manager - User Full Name,User - Manager - User Email
496,Sean,Johnson,Sean Johnson,Great Lakes - Area,"Eau Claire, WI - Market",Outside Account Executive - 100% Commission,SeanJohnson@iheartmedia.com,"Hencley, Rick",RICKHENCLEY@iheartmedia.com

In [5]:
revenue[revenue.apply(lambda row: row.astype(str).str.contains('marcus', case=False).any(), axis=1)].head()

,opportunity_id,stage,market_division,market_area,market,ae_name,new_business,account,opportunity,project_id,form_date,opportunity_created_date,opportunity_closed_date,gross_expected_revenue,gross_amount,form_created_on_closed_opp,market_type
5,0060y00001EBeNY,Closed - Won,MidWest-SouthEast,North FL,Inside Sales,Marcus Cash,Existing Business,"Lineage Logistics, LLC",Lineage Lo-Baltimore/DC Hiring-Inside Sales-83...,A5REIDFAAAA,20200622,6/16/2020,6/25/2020,51265.67,51265.67,0,NaN
139,0060y00001FzdrI,Qualified (CNA),MidWest-SouthEast,North FL,Inside Sales,Marcus Cash,New Business,iHeartMedia+Entertainment Inc,iHeartMedi-AD Wire Production Request-Inside S...,B48duAHgAAA,20210107,1/7/2021,2/5/2021,0.00,0.00,0,NaN
140,0060y00001FzdrI,Qualified (CNA),MidWest-SouthEast,North FL,Inside Sales,Marcus Cash,New Business,iHeartMedia+Entertainment Inc,iHeartMedi-AD Wire Production Request-Inside S...,B48eSRBAAAA,20210107,1/7/2021,2/5/2021,0.00,0.00,0,NaN
2385,0060y00001DchQj,Closed - Lost,Abromovich,Delta,MemphisTN,Marcus Woods,New Business,Southern Hands Home Style Cooking,Souther Ha-Southern Hands Home Style Cook-APR ...,Agm4ZCNwAAA,20200408,4/8/2020,4/22/2020,0.00,0.00,0,Community
7448,0060y00001DLmeW,Closed - Lost,Abromovich,Delta,MemphisTN,Marcus Woods,New Business,FURNITURE DEPOT,"HOLLAND LA-Furniture Depot revision-Woods, Mar...",AgOnMCRAAAE,20200407,4/7/2020,4/23/2020,0.00,0.00,0,Community

In [9]:
projects[projects.apply(lambda row: row.astype(str).str.contains('marcus.cash', case=False).any(), axis=1)]

,project_id,create_ts,email,title,name,name.1,group,submissions,opportynity_id,credits_used,industry,tone,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
1469,9b511d44-e842-11e8-98e2-0ac7678cb9c1,2018-11-14 14:22:21,marcuscash@iheartmedia.com,Lucky Lincoln Holiday Script,AdWire Final Scripts | 15 or 30 Seconds,Marcus Cash,"St. Petersburg, FL | Inside Sales",11,SFO-5767930,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7975,A5REIDFAAAA,2020-06-22 14:01:45,marcuscash@iheartmedia.com,"Lineage Logistics, LLC | Hiring Push",AdWire Draft Scripts | 30 Seconds,Marcus Cash,"St. Petersburg, FL | Inside Sales",6,0060y00001EBeNYAA1,1,Transportation Svcs,Serious,NaN,NaN,NaN,NaN,NaN
18234,B48duAHgAAA,2021-01-07 14:42:48,marcuscash@iheartmedia.com,iHeartMedia+Entertainment Inc,AdWire Final Scripts | 15 Seconds,Marcus Cash,"St. Petersburg, FL | Inside Sales",6,0060y00001FzdrIAAR,1,Media & Publishing,Serious,NaN,NaN,NaN,NaN,NaN
18235,B48eSRBAAAA,2021-01-07 14:45:14,marcuscash@iheartmedia.com,iHeartMedia+Entertainment Inc,AdWire Final Scripts | 30 Seconds,Marcus Cash,"St. Petersburg, FL | Inside Sales",6,0060y00001FzdrIAAR,1,Media & Publishing,Serious,NaN,NaN,NaN,NaN,NaN

In [15]:
workday[workday.apply(lambda row: row.astype(str).str.contains('seanjohnson', case=False).any(), axis=1)]

,action,client code,email,first name,last name,group
236,ADD,iheart,SeanJohnson@iheartmedia.com,Sean,Johnson,"Eau Claire, WI"

## Ownership appending

#### Read-in HR report, usership table, Monday.com export, workday report, revenue report, projects table
#### Create lists of markets by owner
#### Append owner's name in new "owner" column in user_df

In [6]:
# # Creates a list for each team member of the markets he/she owns
# Casts group names to lowercase to aid in matching
user_df['group_upper'] = user_df.group + ''
user_df.group = user_df['group'].str.lower()
# Casts market names to lowercase to aid in matching
market_owners.Name = market_owners.Name.str.lower()

arliss = market_owners[market_owners['Owner'] == 'Arliss Coates']
arliss = arliss.Name.tolist()
ashley = market_owners[market_owners['Owner'] == 'Ashley McCarthy']
ashley = ashley['Name'].tolist()
jenny = market_owners[market_owners['Owner'] == 'Jenny Donheiser']
jenny = jenny['Name'].tolist()
mariana = market_owners[market_owners['Owner'] == 'Mariana E Trevino Stafford']
mariana = mariana['Name'].tolist()

# Strips whitespace from group names in user_df
user_df.group = user_df.group.str.strip()

# # Slicing user_df by market owner

arliss_users = user_df.loc[user_df['group'].isin(arliss)]
ashley_users = user_df.loc[user_df['group'].isin(ashley)]
jenny_users = user_df.loc[user_df['group'].isin(jenny)]
mariana_users = user_df.loc[user_df['group'].isin(mariana)]

print('arliss_users: ' + str(arliss_users.shape), '\n'
'ashley_users: ' + str(ashley_users.shape), '\n'
'jenny_users: ' + str(jenny_users.shape), '\n'
'mariana_users: ' + str(mariana_users.shape))

print('arliss projects/users: ' + str(arliss_users.projects.sum()/arliss_users.shape[0]), '\n'
      'arliss projects: ' + str(arliss_users.projects.sum()), '\n'
      'ashley projects/users: ' + str(ashley_users.projects.sum()/arliss_users.shape[0]), '\n'
      'ashley projects: ' + str(ashley_users.projects.sum()), '\n'
      'jenny projects/users: ' + str(jenny_users.projects.sum()/arliss_users.shape[0]), '\n'
      'jenny projects: ' + str(jenny_users.projects.sum()), '\n'
      'mariana projects/users: ' + str(mariana_users.projects.sum()/arliss_users.shape[0]), '\n'
      'mariana projects: ' + str(mariana_users.projects.sum()))

print('arliss groups in user_df: ' + str(len(arliss_users.group.unique())), '\n'
      'arliss groups in market_owners :' + str(len(arliss)))
print('ashley groups in user_df: ' + str(len(ashley_users.group.unique())), '\n'
      'ashley groups in market_owners: ' + str(len(ashley)))
print('jenny groups in user_df: ' + str(len(jenny_users.group.unique())), '\n'
      'jenny groups in market_owners: ', len(jenny))
print('mariana groups in user_df: ', len(mariana_users.group.unique()), '\n'
      'mariana groups in market_owners: ', len(mariana))
print('users_df shape: ' + str(user_df.shape))
print('empl_roll shape: ' + str(empl_roll.shape))

arliss_users: (779, 9)
ashley_users: (917, 9)
jenny_users: (774, 9)
mariana_users: (495, 9)
arliss projects/users: 7.2477535301668805
arliss projects: 5646
ashley projects/users: 5.388960205391528
ashley projects: 4198
jenny projects/users: 5.993581514762516
jenny projects: 4669
mariana projects/users: 4.2092426187419765
mariana projects: 3279
arliss groups in user_df: 47
arliss groups in market_owners :48
ashley groups in user_df: 39
ashley groups in market_owners: 40
jenny groups in user_df: 35
jenny groups in market_owners:  37
mariana groups in user_df:  24
mariana groups in market_owners:  25
users_df shape: (3209, 9)
empl_roll shape: (2183, 17)

#### Defines variable "frames" as a list of the user_df subsets so as
#### to concatenate them in the following line. Redefining variable "user_df"
#### as the same dataframe but with "owner" column added.

In [7]:
# # Adding new field "owner" to each team member's subset of user_df for the purpose of concatenating
# # these dataframes in the following code
arliss_users['owner'] = 'Arliss'
ashley_users['owner'] = 'Ashley'
jenny_users['owner'] = 'Jenny'
mariana_users['owner'] = 'Mariana'

frames = [arliss_users, ashley_users, jenny_users, mariana_users]
user_df = pd.concat(frames)

user_df.to_csv('ihm_users_with_owner.csv', index = 0)

empl_roll['Email - Primary Work'] = empl_roll['Email - Primary Work'].str.lower()
empl_roll.rename(columns = {'Email - Primary Work': 'email'}, inplace=True)

user_df.email = user_df.email.str.lower()
filtered_users = user_df.groupby('email').filter(lambda x : len(x)==1)

empl_roll.Market = empl_roll.Market.str.lower()
empl_roll.Market = [x.replace(' - market', '') for x in empl_roll.Market]

merged = pd.DataFrame(pd.merge(user_df, empl_roll, on='email', how='outer'))

merged.to_csv('merged_hr_and_users.csv')

print('user_df shape is: ', user_df.shape, '\n'
     'empl_roll shape is: ', empl_roll.shape ,'\n'
     'registered users minus employees on file: ', user_df.shape[0] - empl_roll.shape[0], '\n'
     'merged shape is: ', merged.shape)

merged.loc[merged['name'].str.split().str.len() == 2, 'first name'] = merged['name'].str.split().str[0]

# virginia = merged.loc[(merged.projects <= 5) &
#                      (merged['Region/Area'].str.contains('Virginia')) &
#                      merged['Job Title'].str.contains('Acc')].groupby('email').filter(lambda x : len(x)== 1)[['email', 'first name', 'Market', 'projects']]
# virginia

/Users/arlisscoates/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/arlisscoates/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/Users/arlisscoates/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Users/arlisscoates/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

user_df shape is:  (2965, 10)
empl_roll shape is:  (2183, 17)
registered users minus employees on file:  782
merged shape is:  (3464, 26)

In [8]:
# empl_roll, user_df, workday
allmerge = pd.DataFrame(pd.merge(merged, workday,  on='email', how='outer'))

deletes = workday.loc[workday.action == 'DELETE'].action.tolist()

allmerge.to_csv('allmerge.csv')

projects.opportynity_id = projects.opportynity_id.astype(str)

projects.opportynity_id = [x[:15] for x in projects.opportynity_id]

project_merge = pd.DataFrame(pd.merge(revenue, projects, on='project_id', how='outer'))

projects_people_merge = pd.DataFrame(pd.merge(allmerge, project_merge, on='email', how='outer'))

projects_people_merge.rename(columns = {'client': 'adwire_client', 'group_x': 'adwire_group', 'name_x': 'adwire_name_x',
                                       'email': 'adwire_email', 'projects': 'adwire_projects', 'spend': 'adwire_spend',
                                       'project_ts': 'adwire_first_posting', 'group_cap': 'adwire_cap', 'owner': 'account_owner',
                                        'group_upper': 'adwire_group_upper',
                                       'Worker': 'hr_worker', 'Job Title': 'hr_job_title', 'Business Title': 'hr_business_title',
                                       'Hire Date': 'hr_hire_date', 'Phone - Primary Work': 'hr_work_phone',
                                       'Mobile Phones': 'hr_mobile_phone', "Worker's Manager": 'hr_worker_manager',
                                        "Worker's Manager Business Title": "hr_worker_manager_business_title",
                                       "Worker's Manager's Manager": "hr_worker_manager_manager",
                                       "Worker's Manager's Manager Business Title": "hr_worker_manager_manager_business_title",
                                       'Market': 'hr_market', 'Market President': 'hr_market_president', 'Region/Area': 'hr_region_area',
                                       'Area/Region/Community President': 'hr_area_region_community_president', 'Division': 'hr_division',
                                       'Division President': 'hr_division_president', 'first name_x': 'workday_first_name', 
                                       'action': 'workday_action', 'client code': 'workday_client_code', 'first name_y': 'workday_first_name2',
                                       'last name': 'workday_last_name', 'group_y': 'workday_group_y', 'Opportunity: Opportunity ID': 'revenue_opportunity_id', 'stage': 'revenue_stage',
                                        'market_division': 'revenue_market_division', 'market_area': 'revenue_market_area', 'market': 'revenue_market',
                                       'ae_name': 'revenue_ae_name', 'new_business': 'revenue_new_business', 'account': 'revenue_account',
                                       'opportunity': 'revenue_opportunity', 'project_id': 'adwire_project_id', 'form_date': 'revenue_form_date',
                                       'opportunity_created_date': 'revenue_opportunity_created_date', 'opportunity_closed_date': 'revenue_opportunity_closed_date',
                                       'gross_expected_revenue': 'revenue_gross_expected_revenue', 'gross_amount': 'revenue_gross_amount',
                                        'form_created_on_closed_opp': 'revenue_form_created_on_closed_opp',
                                       'market_type': 'revenue_market_type', 'create_ts': 'adwire_post_date', 'name_y': 'adwire_name_y',
                                       'group': 'adwire_group2', 'submissions': 'adwire_submissions', 'opportynity_id': 'adwire_opportunity_id',
                                       'credits_used': 'adwire_credits_used', 'industry': 'adwire_industry', 'tone': 'adwire_tone'}, inplace=True)

print('the shape of projects_people_merge is: ' + str(projects_people_merge.shape))

the shape of projects_people_merge is: (27109, 64)

# Mutates column "revenue_formatted_market"

In [9]:
projects_people_merge.revenue_market = projects_people_merge.revenue_market.astype(str)

df4 = projects_people_merge

str_list = df4.revenue_market

a = str_list
b = a.to_list()

c = [x[:-2] for x in b]
d = [x[-2:] for x in b]

f = ['iHeart Media - '+ i + ', ' + j for i, j in zip(c, d)]

df5 = pd.DataFrame({"formatted_market": f})

df5.loc[(df5['formatted_market'] == 'iHeart Media - Inside Sal, es'),'formatted_market'] = 'iHeart Media - Inside Sales'
df5.loc[(df5['formatted_market'] == 'iHeart Media - WestPalmBeach, FL'), 'formatted_market'] = 'iHeart Media - West Palm Beach, FL'
df5.loc[(df5['formatted_market'] == 'iHeart Media - CorpusChristi, TX'), 'formatted_market'] = 'iHeart Media - Corpus Christi, TX'
df5.loc[(df5['formatted_market'] == 'iHeart Media - SanAntonio, TX'), 'formatted_market'] = 'iHeart Media - San Antonio, TX'
df5.loc[(df5['formatted_market'] == 'iHeart Media - ElPaso, TX'), 'formatted_market'] = 'iHeart Media - El Paso, TX'
df5.loc[(df5['formatted_market'] == 'iHeart Media - NewHaven, CT'), 'formatted_market'] = 'iHeart Media - New Haven, CT'
df5.loc[(df5['formatted_market'] == 'iHeart Media - FortMyers, FL'), 'formatted_market'] = 'iHeart Media - Fort Myers/Naples, FL'
df5.loc[(df5['formatted_market'] == 'iHeart Media - SiouxCity, IA'), 'formatted_market'] = 'iHeart Media - Sioux City, IA'
df5.loc[(df5['formatted_market'] == 'iHeart Media - SaltLakeCity, UT'), 'formatted_market'] = 'iHeart Media - Salt Lake City, UT'
df5.loc[(df5['formatted_market'] == 'iHeart Media - MyrtleBeach, SC'), 'formatted_market'] = 'iHeart Media - Myrtle Beach, SC'
df5.loc[(df5['formatted_market'] == 'iHeart Media - FortCollins, CO'), 'formatted_market'] = 'iHeart Media - Fort Collins, CO'
df5.loc[(df5['formatted_market'] == 'iHeart Media - LosAngeles, CA'), 'formatted_market'] = 'iHeart Media - Los Angeles, CA'
df5.loc[(df5['formatted_market'] == 'iHeart Media - ColoradoSprings, CO'), 'formatted_market'] = 'iHeart Media - Colorado Springs, CO'
df5.loc[(df5['formatted_market'] == 'iHeart Media - NewOrleans, LA'), 'formatted_market'] = 'iHeart Media - New Orleans, LA'
df5.loc[(df5['formatted_market'] == 'iHeart Media - BatonRouge, LA'), 'formatted_market'] = 'iHeart Media - Baton Rouge, LA'
df5.loc[(df5['formatted_market'] == 'iHeart Media - GrandForks, ND'), 'formatted_market'] = 'iHeart Media - El Paso, TX'
df5.loc[(df5['formatted_market'] == 'iHeart Media - LasVegas, NV'), 'formatted_market'] = 'iHeart Media - Las Vegas, NV'
df5.loc[(df5['formatted_market'] == 'iHeart Media - CedarRapids, IA'), 'formatted_market'] = 'iHeart Media - Cedar Rapids/Iowa City, IA'
df5.loc[(df5['formatted_market'] == 'iHeart Media - CapeCod, MA'), 'formatted_market'] = 'iHeart Media - Cape Cod, MA'
df5.loc[(df5['formatted_market'] == 'iHeart Media - FortSmith, AR'), 'formatted_market'] = 'iHeart Media - Fort Smith, AR'
df5.loc[(df5['formatted_market'] == 'iHeart Media - GrandRapids, MI'), 'formatted_market'] = 'iHeart Media - Grand Rapids, MI'
df5.loc[(df5['formatted_market'] == 'iHeart Media - DesMoines, IA'), 'formatted_market'] = 'iHeart Media - Des Moines, IA'
df5.loc[(df5['formatted_market'] == 'iHeart Media - SaintLouis, MO'), 'formatted_market'] = 'iHeart Media - Saint Louis, MO'
df5.loc[(df5['formatted_market'] == 'iHeart Media - BayArea, CA'), 'formatted_market'] = 'iHeart Media - San Francisco, CA'
df5.loc[(df5['formatted_market'] == 'iHeart Media - PanamaCity, FL'), 'formatted_market'] = 'iHeart Media - Panama City/Tallahassee, FL'
df5.loc[(df5['formatted_market'] == 'iHeart Media - OklahomaCity, OK'), 'formatted_market'] = 'iHeart Media - Oklahoma City, OK'
# df5.loc[(df5['formatted_market'] == 'iHeart Media - n, an'), 'formatted_market'] = 'iHeart Media - National Sales'
df5.loc[(df5['formatted_market'] == 'iHeart Media - EauClaire, WI'), 'formatted_market'] = 'iHeart Media - Eau Claire, WI'
df5.loc[(df5['formatted_market'] == 'iHeart Media - SanDiego, CA'), 'formatted_market'] = 'iHeart Media - San Diego, CA'
df5.loc[(df5['formatted_market'] == 'iHeart Media - LittleRock, AR'), 'formatted_market'] = 'iHeart Media - Little Rock, AR'
df5.loc[(df5['formatted_market'] == 'iHeart Media - El Paso, TX'), 'formatted_market'] = 'iHeart Media - El Paso, TX'
df5.loc[(df5['formatted_market'] == 'iHeart Media - Roanoke, VA'), 'formatted_market'] = 'iHeart Media - Roanoke/Lynchburg, VA'
df5.loc[(df5['formatted_market'] == 'iHeart Media - Sarasota, FL'), 'formatted_market'] = 'iHeart Media - Sarasota/Bradenton, FL'
df5.loc[(df5['formatted_market'] == 'iHeart Media - Ashland, OH'),'formatted_market'] = 'iHeart Media - Ashland/Mansfield, OH'
df5.loc[(df5['formatted_market'] == 'iHeart Media - NewYork, NY'),'formatted_market'] = 'iHeart Media - New York City, NY'
df5.loc[(df5['formatted_market'] == 'iHeart Media - Modesto, CA'),'formatted_market'] = 'iHeart Media - Modesto/Stockton, CA'
df5.loc[(df5['formatted_market'] == 'iHeart Media - Hattiesburg, MS'),'formatted_market'] = 'iHeart Media - Laurel, MS'
df5.loc[(df5['formatted_market'] == 'iHeart Media - Albany, GA'),'formatted_market'] = 'iHeart Media - Columbus, GA'

df6 = pd.concat([projects_people_merge,df5], axis=1)

df6 = df6.rename(columns = {'formatted_market': 'account'})

df6.drop(df6[df6.workday_action == 'ADD'].index, inplace = True) 

df6.fillna('No Data', inplace = True)

In [10]:
df6['account'] = np.where(df6.account == 'iHeart Media - n, an', 'iHeart Media - ' + df6.adwire_group_upper, df6.account)
df6['account'] = np.where(df6.account == 'iHeart Media - No Data', df6.adwire_group2, df6.account)
df6['account'] = np.where(df6.account == 'No Data', df6.hr_market, df6.account)
df6['account'] = np.where(df6.account == 'No Data', df6.workday_group_y, df6.account)
df6['account'] = np.where(df6.account == 'No Data', df6.revenue_market, df6.account)
df6['account'] = np.where(df6.account == 'nan', 'No Data', df6.account)

df6.account = df6.account.apply(lambda x: x.strip())
df6 = df6[(df6.adwire_name_x != 'James Palmiotto') | (df6.adwire_name_x != 'David Liu') | (df6.adwire_name_x != 'Louis Wortelman') | (df6.adwire_name_x != 'Dan Lankford')]

df6.account = df6.account.str.title()
df6.account = [x.replace('Iheart Media - ', '') for x in df6.account]
df6.account = df6.account.map(lambda x: 'iHeart Media - ' + x[0:-2] + x[-2:].upper()) 
df6.account = [re.sub(r'(?:(?<=\/) | (?=\/))','',x) for x in df6.account]

df6.loc[(df6.account == 'iHeart Media - Inside SalES', 'account')] = 'iHeart Media - Inside Sales'
df6.loc[(df6.account == 'iHeart Media - Inside Sales & Bus DevelopmeNT', 'account')] = 'iHeart Media - Inside Sales'
df6.loc[(df6.account == 'iHeart Media - Sales OperatiON', 'account')] = 'iHeart Media - Sales Operation'
df6.loc[(df6.account == 'iHeart Media - Revenue ManagemeNT', 'account')] = 'iHeart Media - Revenue Management'
df6.loc[(df6.account == 'iHeart Media - Govt InitiativES', 'account')] = 'iHeart Media - Govt Initiatives'
df6.loc[(df6.account == 'iHeart Media - Integrated Revenue StrategiES', 'account')] = 'iHeart Media - Integrated Revenue Strategies'
df6.loc[(df6.account == 'iHeart Media - Centralized DigitAL', 'account')] = 'iHeart Media - Centralized Digital'
df6.loc[(df6.account == 'iHeart Media - Auto TeAM', 'account')] = 'iHeart Media - Auto Team'
df6.loc[(df6.account == 'iHeart Media - Markets Events TeAM', 'account')] = 'iHeart Media - Markets Events Team'
df6.loc[(df6.account == 'iHeart Media - Design HUB', 'account')] = 'iHeart Media - Design Hub'
df6.loc[(df6.account == 'iHeart Media - St. Petersburg, Fl | Inside SalES', 'account')] = 'iHeart Media - Inside Sales'
df6.loc[(df6.account == 'iHeart Media - St Petersburg , FL', 'account')] = 'iHeart Media - Inside Sales'
df6.loc[(df6.account == 'iHeart Media - No DaTA', 'account')] = 'iHeart Media - No Data'
df6.loc[(df6.account == 'iHeart Media - Integrated Revenue StrateGY', 'account')] = 'iHeart Media - Integrated Revenue Strategies'

names = ['DAN LANKFORD', 'Dan Lankford', 'dan lankford', 'JAMES PALMIOTTO', 'James Palmiotto', 'james palmiotto',
        'DAVID LIU', 'David Liu', 'david liu', 'LOUIS WORTELMANN', 'Louis Wortelmann', 'louis wortelmann']

df6 = df6[~df6.adwire_name_x.isin(names)]

df6.loc[df6.account == 'iHeart Media - No Data'].to_csv('no_market_data.csv')

In [11]:
df6.drop(df6[df6.account == 'iHeart Media - No Data'].index, inplace = True)
df6.to_csv('fullmerge.csv', index = 0)

In [12]:
# df6.drop(df6[df6.adwire_project_id == 'No Data'].index, inplace = True)
# df6.drop_duplicates(subset = ['adwire_project_id'], inplace=True)
# df6.shape
# # df6.to_csv('testmerge.csv')

In [13]:
leftprojects = projects.merge(revenue, on='project_id', how='left', indicator=True)
leftprojects.head()

,project_id,create_ts,email,title,name,name.1,group,submissions,opportynity_id,credits_used,industry,tone,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,opportunity_id,stage,market_division,market_area,market,ae_name,new_business,account,opportunity,form_date,opportunity_created_date,opportunity_closed_date,gross_expected_revenue,gross_amount,form_created_on_closed_opp,market_type,_merge
0,29edde17-6d86-11e8-9f89-0ac7678cb9c1,2018-06-11 10:46:03,masonparrish@iheartmedia.com,PENN FC,AdWire | Radio Ad Ideas + Draft Script,Mason Parrish,"St. Petersburg, FL | Inside Sales",18,MasonP1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,6bd3b41c-6db3-11e8-9f89-0ac7678cb9c1,2018-06-11 16:10:01,samgerb@iheartmedia.com,Banana Beach Tan,AdWire | Radio Ad Ideas + Draft Script,Sam Gerb,"St. Petersburg, FL | Inside Sales",10,SFO-5168157,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,32f41d0e-6db4-11e8-9f89-0ac7678cb9c1,2018-06-11 16:15:35,debracreelman@iheartmedia.com,"Flawless Med Spa: Julie Kalsi Beri, DO",AdWire | Radio Ad Ideas + Draft Script,Debra Creelman,"St. Petersburg, FL | Inside Sales",9,SFO-4883207,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,cb106404-6db4-11e8-9f89-0ac7678cb9c1,2018-06-11 16:19:50,jeffreycroy@iheartmedia.com,Sprague Roofing,AdWire | Radio Ad Ideas + Draft Script,Jeff Croy,"St. Petersburg, FL | Inside Sales",2,PattyRacener1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,ebec1a77-6db4-11e8-9f89-0ac7678cb9c1,2018-06-11 16:20:45,christinasovich@iheartmedia.com,Chicago the Musical,AdWire | Radio Ad Ideas + Draft Script,Christina Sovich,"St. Petersburg, FL | Inside Sales",13,https://ihm.my.,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [14]:
pd.DataFrame(df6.account.unique().tolist()).to_csv('account_names.csv')

In [15]:

# empl_roll.rename(columns = {'Worker': 'hr_worker', 'Job Title': 'hr_job_title', 'Business Title': 'hr_business_title',
#                                        'Hire Date': 'hr_hire_date', 'Phone - Primary Work': 'hr_work_phone',
#                                        'Mobile Phones': 'hr_mobile_phone', "Worker's Manager": 'hr_worker_manager',
#                                         "Worker's Manager Business Title": "hr_worker_manager_business_title",
#                                        "Worker's Manager's Manager": "hr_worker_manager_manager",
#                                        "Worker's Manager's Manager Business Title": "hr_worker_manager_manager_business_title",
#                                        'Market': 'hr_market', 'Market President': 'hr_market_president', 'Region/Area': 'hr_region_area',
#                                        'Area/Region/Community President': 'hr_area_region_community_president', 'Division': 'hr_division',
#                                        'Division President': 'hr_division_president'}, inplace=True)

# user_df.rename(columns = {'client': 'adwire_client', 'group_x': 'adwire_group', 'name_x': 'adwire_name_x',
#                                        'email': 'adwire_email', 'projects': 'adwire_projects', 'spend': 'adwire_spend',
#                                        'project_ts': 'adwire_first_posting', 'group_cap': 'adwire_cap', 'owner': 'account_owner',
#                                         'group_upper': 'adwire_group_upper'}, inplace=True)

# workday.rename(columns = {'first name_x': 'workday_first_name', 
#                                        'action': 'workday_action', 'client code': 'workday_client_code', 'first name_y': 'workday_first_name2',
#                                        'last name': 'workday_last_name', 'group_y': 'workday_group_y'}, inplace=True)

# revenue.rename(columns = {'Opportunity: Opportunity ID': 'revenue_opportunity_id', 'stage': 'revenue_stage',
#                                         'market_division': 'revenue_market_division', 'market_area': 'revenue_market_area', 'market': 'revenue_market',
#                                        'ae_name': 'revenue_ae_name', 'new_business': 'revenue_new_business', 'account': 'revenue_account',
#                                        'opportunity': 'revenue_opportunity', 'project_id': 'adwire_project_id', 'form_date': 'revenue_form_date',
#                                        'opportunity_created_date': 'revenue_opportunity_created_date', 'opportunity_closed_date': 'revenue_opportunity_closed_date',
#                                        'gross_expected_revenue': 'revenue_gross_expected_revenue', 'gross_amount': 'revenue_gross_amount',
#                                         'form_created_on_closed_opp': 'revenue_form_created_on_closed_opp',
#                                        'market_type': 'revenue_market_type'}, inplace=True)

# projects.rename(columns = {'create_ts': 'adwire_post_date', 'name_y': 'adwire_name_y',
#                                        'group': 'adwire_group2', 'submissions': 'adwire_submissions', 'opportynity_id': 'adwire_opportunity_id',
#                                        'credits_used': 'adwire_credits_used', 'industry': 'adwire_industry', 'tone': 'adwire_tone'}, inplace=True)

In [16]:
empl_roll.to_csv('empl_roll.csv')
user_df.to_csv('user_df.csv')
workday.to_csv('workday.csv')
revenue.to_csv('revenue.csv')
projects.to_csv('projects.csv')

In [17]:
newhr['User - Division'] = [x.replace(' - Market', '').lower() for x in newhr['User - Division']]
arlissmanagers_hr = [x for x in newhr.loc[newhr['User - Division'].isin(arliss)].loc[newhr["User - Position"].str.contains('Account Exec')]["User - Manager - User Email"].unique().tolist()]

arliss_newhr_df = newhr.loc[newhr['User - User Email'].isin(arlissmanagers_hr)]
# [['First Name', 'User - User Email', 'User - Position','User - Division']]
arliss_newhr_markets = newhr.loc[newhr['User - User Email'].isin(arlissmanagers_hr)][['First Name', 'User - User Email', 'User - Position','User - Division']]['User - Division'].unique().tolist()
missing_markets = [x for x in arliss if x not in arliss_newhr_markets]

missing_managers = newhr.loc[newhr['User - Division'].isin(missing_markets)]['User - Manager - User Email']
missing_df = newhr.loc[newhr['User - User Email'].isin(missing_managers)]
frames = (missing_df, arliss_newhr_df)
all_managers = pd.DataFrame(pd.concat(frames))[['First Name', 'User - Division', 'User - User Email']]

data = {'First Name': ['Kristen', 'Brit', 'Matt', 'Bob', 'Wendy', 'Ron', 'Craig', 'Ryan', 'Rick', 'Chuck', 'Vicki', 'Greg', 'Rhonda', 'Mike', 'Brent'],
        'User - Division': ['albany, ny','allentown, pa', 'ashland/mansfield, oh', 'binghamton, ny', 'bismarck, nd', 'charleston, sc', 'chillicothe, oh', 'denver, co', 'eau claire, wi', 'harrisonburg, va',
                           'new haven, ct', 'minneapolis, mn', 'ogallala, ne', 'raleigh, nc', 'spokane, wa'], 'User - User Email': market_owners.loc[market_owners.Owner == 'Arliss Coates']['Email'].unique().tolist()}
completemanagersframes = (pd.DataFrame(data=data), all_managers)
all_managers = pd.concat(completemanagersframes)
all_managers['User - User Email'] = all_managers['User - User Email'].str.lower()
all_managers.drop_duplicates(subset = ['User - User Email'],inplace=True)
all_managers.sort_values(by='User - Division',inplace=True)
all_managers.to_csv('arliss_managers.csv')

In [130]:
# newhr.loc[newhr.Name.str.contains('robinson',case=False,na=False)]

In [131]:
# revenue.loc[revenue.ae_name.str.contains('monica robinson',case=False,na=False)]

In [133]:
user_df.loc[user_df.name.str.contains('McKenzie',case=False,na=False)]
# user_df.loc[user_df.name == 'McKenzie Bond']

,client,group,name,email,projects,spend,project_ts,group_cap,group_upper,owner
1042,iHeart Media,"miami, fl",mark mckenzie,markmckenzie@iheartmedia.com,3,4.5,2020-07-22 17:33:18,52,"Miami, FL",Mariana

In [97]:
projects.loc[projects['name.1'].str.contains('mckenzie',case=False, na=False)]

In [104]:
leftprojects.loc[leftprojects['ae_name'].str.contains('monica robinson',na=False,case=False)]

,project_id,create_ts,email,title,name,name.1,group,submissions,opportynity_id,credits_used,industry,tone,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,opportunity_id,stage,market_division,market_area,market,ae_name,new_business,account,opportunity,form_date,opportunity_created_date,opportunity_closed_date,gross_expected_revenue,gross_amount,form_created_on_closed_opp,market_type,_merge
7131,AzpRRAOwAAA,2020-06-05 12:39:46,PaulBostonKelley@iheartmedia.com,New Hampshire Bankruptcy Law | Proposal for NH...,AdWire Draft Scripts | 30 Seconds,PAUL KELLEY,"Manchester, NH",6,0060y00001EAsTw,1,Professional Services,Serious,NaN,NaN,NaN,NaN,NaN,0060y00001EAsTw,Closed - Lost,MidWest-SouthEast,Atlanta,NaN,Monica Robinson,Existing Business,"C&S WHOLESALE GROCERS, INC.",C&S WHOLES-C&S Wholesale Grocers_ Boston_ Q4 2...,20200605.0,6/5/2020,8/27/2020,0.0,99960.0,0.0,NaN,both
9843,BFdl3HpgAAA,2020-07-29 14:05:43,andrewhoops@iheartmedia.com,Flight Fit N Fun LLC | MURFREESBORO Opening,AdWire Draft Scripts | 30 Seconds,Andrew Hoops,"Hartford, CT",8,0060y00001EekrZ,1,Entertainment,Funny,NaN,NaN,NaN,NaN,NaN,0060y00001EekrZ,Closed - Lost,MidWest-SouthEast,Atlanta,NaN,Monica Robinson,Existing Business,Flight Fit N Fun LLC,Flight Fit-Flight Fit N Fun_ Nashville_ Sept-N...,20200729.0,7/28/2020,9/15/2020,0.0,15000.0,0.0,NaN,both
10185,BHy2EIOAAAA,2020-08-05 15:54:44,katediscavage@iheartmedia.com,Flashfood | Flashfood launching in Detroit,AdWire Draft Scripts | 30 Seconds,Kate Discavage,"Lancaster, PA",5,0060y00001EemD6,1,Miscellaneous,I don't care as long as it's good,NaN,NaN,NaN,NaN,NaN,0060y00001EemD6,Closed - Won,MidWest-SouthEast,Atlanta,NaN,Monica Robinson,Existing Business,Flashfood,Flashfood-Flashfood_Detroit_ Sept-Oct 2020-MMS...,20200805.0,7/28/2020,8/14/2020,28000.0,28000.0,0.0,NaN,both
11297,BQZ_jDBwAAA,2020-08-31 18:59:48,BradPeterson@iheartmedia.com,Miracle Windows and SunRooms | Miracle 25K Mak...,AdWire Draft Scripts | 30 Seconds,Brad Peterson,"Houston, TX",8,0060y00001EDH9F,1,Home Building/Improvement,I don't care as long as it's good,NaN,NaN,NaN,NaN,NaN,0060y00001EDH9F,Closed - Won,MidWest-SouthEast,Atlanta,NaN,Monica Robinson,Existing Business,Miracle Windows and SunRooms,Miracle Wi-Miracle Windows and SunRooms_Jackso...,20200831.0,7/9/2020,7/31/2020,41550.0,41550.0,1.0,NaN,both
12945,BcLr7ADAAAA,2020-10-06 12:31:56,rossdecastro@iheartmedia.com,ACLU Foundation Of Georgia Inc | Poll Worker C...,AdWire Draft Scripts | 60 Seconds,Ross De Castro,"Columbus, GA",5,0060y00001F9HNJ,1.5,Not-For-Profit/Charitable/Religious,I don't care as long as it's good,NaN,NaN,NaN,NaN,NaN,0060y00001F9HNJ,Closed - Won,MidWest-SouthEast,Atlanta,NaN,Monica Robinson,Existing Business,ACLU Foundation Of Georgia Inc,ACLU Found-ACLU Foundation of GA_ Oct 2020-MMS...,20201006.0,10/2/2020,10/7/2020,17895.0,17895.0,0.0,NaN,both
15674,Bqu0CGDQAAA,2020-11-19 14:56:51,Alangreen@iheartmedia.com,Certain Supply,AdWire Draft Scripts | 30 Seconds,Alan Green,"Albany, NY",5,0060y00001FakTI,1,Medical/Healthcare,No preference. I'm open to a range of good ideas.,NaN,NaN,NaN,NaN,NaN,0060y00001FakTI,Closed - Lost,MidWest-SouthEast,Atlanta,NaN,Monica Robinson,New Business,Certain Supply,Certain Su-Certain Supply_ LA_ Q1 2021-MMS-896...,20201119.0,11/4/2020,2/17/2021,0.0,60000.0,0.0,NaN,both
17574,BzpHyHEwAAA,2020-12-16 15:49:55,kellyleclair@iheartmedia.com,Swanky Smiles,AdWire Draft Scripts | 15 AND 30 Seconds,Kelly LeClair,"Hartford, CT",8,0060y00001FdLNw,2.5,Medical/Healthcare,Funny,NaN,NaN,NaN,NaN,NaN,0060y00001FdLNw,Closed - Lost,MidWest-SouthEast,Atlanta,NaN,Monica Robinson,New Business,Swanky Smiles,Swanky Smi-Swanky Smiles_ Houston_ Jan-Jul 202...,20201216.0,12/15/2020,2/23/2021,0.0,120000.0,0.0,NaN,both
22221,B_28bhEAAAA,2021-04-01 13:29:18,katediscavage@iheartmedia.com,Flashfood | Flashfood partnering with Giant Gr...,AdWire Draft Scripts | 30 Seconds,Kate Discavage,"Lancaster, PA",6,0060y00001FpWJf,1,Food & Beverage,No preference. I'm open to a range of good ideas.,NaN,NaN,NaN,NaN,NaN,0060y00001FpWJf,Proposal Built,MidWest-SouthEast,Atlanta,NaN,Monica Robinson,Existing Business,Flashfood,Flashfood-Flashfood-Flashfood_Pitts_ APR 2021-...,20210401.0,3/24/2021,4/19/2021,2100.0,6000.0,0.0,NaN,both

In [76]:
def Differences(hrnames, accountnames):
    li_diff = [i for i in hrnames + accountnames if i not in hrnames or i not in accountnames]
    missingfromhr = [i for i in hrnames + accountnames if i not in hrnames]
    missingfromnewhr = [i for i in revenue.ae_name.Name.unique().tolist() + newhr.Name.unique().tolist() if i not in newhr.Name.unique().tolist()]
    return 'combined differences:', li_diff, 'missing from table:', missingfromhr, 'missing from accountnames:', missingfromnewhr

In [ ]:
revenue.ae_name = revenue.ae_name.str.lower()
newhr.Name = newhr.Name.str.lower()
projects.name = projects.name.str.lower()
user_df.name = user_df.name.str.lower()

user_df_newhr_list = newhr.Name.unique().tolist() + user_df.name.unique().tolist()
[i for i in revenue.ae_name.unique().tolist() + newhr.Name.unique().tolist() if i not in user_df_newhr_list]

In [29]:
len([i for i in revenue.ae_name.unique().tolist() if i in newhr.Name.unique().tolist()])

1023

In [ ]:
df6['account'] = np.where(df6.account == 'iHeart Media - No Data', df6.adwire_group2, df6.account)
leftprojects = np.where(leftprojects.

In [154]:
# df6[4000:4040]
revenue_newhr.head()
# revenue_newhr.name.value_counts()

,opportunity_id,stage,market_division,market_area,market,name,new_business,account,opportunity,project_id,form_date,opportunity_created_date,opportunity_closed_date,gross_expected_revenue,gross_amount,form_created_on_closed_opp,market_type,First Name,Last Name,User - Division Parent,User - Division,User - Position,User - User Email,User - Manager - User Full Name,User - Manager - User Email,opp_owner_email
0,0060y00001Fo10M,Closed - Won,NaN,NaN,Inside Sales,james boyer,New Business,Nymbl Science,Nymbl Scie-Schroeder-Inside Sales-9399588,B9ZgHBDwAAA,20210302.0,3/1/2021,3/3/2021,3402.0,3402.0,0.0,NaN,James,Boyer,Inside Sales & Business Development,inside sales & bus development,Inside Account Executive - Base + Commission,JamesBoyer@iheartmedia.com,"King, Rich",RichKing@iheartmedia.com,JamesBoyer@iheartmedia.com
1,0060y00001EBr36,Closed - Won,NaN,NaN,Inside Sales,james boyer,Existing Business,Kansept Transportation,Kansept Tr-McCord-Inside Sales-8381318,A6MmmAHQAAA,20200625.0,6/18/2020,6/24/2020,1240.0,1240.0,1.0,NaN,James,Boyer,Inside Sales & Business Development,inside sales & bus development,Inside Account Executive - Base + Commission,JamesBoyer@iheartmedia.com,"King, Rich",RichKing@iheartmedia.com,JamesBoyer@iheartmedia.com
2,0060y00001EdVae,Closed - Won,NaN,NaN,Inside Sales,james boyer,Existing Business,The Marquis Center,"The Marqui-""Marquis Center""-Inside Sales-8627977",BMG8jAXwAAA,20200818.0,8/14/2020,9/17/2020,56950.0,56950.0,0.0,NaN,James,Boyer,Inside Sales & Business Development,inside sales & bus development,Inside Account Executive - Base + Commission,JamesBoyer@iheartmedia.com,"King, Rich",RichKing@iheartmedia.com,JamesBoyer@iheartmedia.com
3,0060y00001Edlju,Closed - Won,NaN,NaN,Inside Sales,james boyer,Existing Business,ACLU of Ohio,ACLU of Oh- MMS Cinci -Inside Sales-8480561,BDgb9ErwAAA,20200723.0,7/14/2020,7/27/2020,3120.0,3120.0,0.0,NaN,James,Boyer,Inside Sales & Business Development,inside sales & bus development,Inside Account Executive - Base + Commission,JamesBoyer@iheartmedia.com,"King, Rich",RichKing@iheartmedia.com,JamesBoyer@iheartmedia.com
4,0060y00001FbTCI,Closed - Lost,NaN,NaN,Inside Sales,james boyer,Existing Business,EcoFreaks,MMS- CA & GA national-EcoFreaks-Vianello-Insid...,BvXbYFCwAAA,20201203.0,11/16/2020,1/7/2021,0.0,46728.0,0.0,NaN,James,Boyer,Inside Sales & Business Development,inside sales & bus development,Inside Account Executive - Base + Commission,JamesBoyer@iheartmedia.com,"King, Rich",RichKing@iheartmedia.com,JamesBoyer@iheartmedia.com

In [125]:
df6['opp_owner_email'] = np.where(df6.revenue_ae_name == df6.adwire_name_x, df6.adwire_email, df6.revenue_ae_name)
df6['opp_owner_email'] = np.where(df6.revenue_ae_name == df6.adwire_name_y, df6.adwire_email, df6.revenue_ae_name)

In [142]:
revenue.rename(columns={'ae_name': 'name'},inplace=True)
newhr.rename(columns={'Name': 'name'},inplace=True)
revenue_newhr = revenue.merge(newhr, on='name',how='outer')

In [148]:
# revenue_newhr.opp_owner_email.value_counts()

In [149]:
revenue_newhr['opp_owner_email'] = revenue_newhr['User - User Email']

In [155]:
workday.head()

,action,client code,email,first name,last name,group
0,ADD,iheart,AaronMarvel@iheartmedia.com,Aaron,Marvel,"San Antonio, TX"
1,ADD,iheart,AaronWerber@iheartmedia.com,Aaron,Werber,"Los Angeles, CA"
2,ADD,iheart,AbbyHunt@iheartmedia.com,Abby,Hunt,"Spokane, WA"
3,ADD,iheart,AbbySutton@iheartmedia.com,Abby,Sutton,"Orlando, FL"
4,ADD,iheart,AdamWolfson@iheartmedia.com,Adam,Wolfson,"Los Angeles, CA"

In [156]:
leftprojects.head()

,project_id,create_ts,email,title,name,name.1,group,submissions,opportynity_id,credits_used,industry,tone,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,opportunity_id,stage,market_division,market_area,market,ae_name,new_business,account,opportunity,form_date,opportunity_created_date,opportunity_closed_date,gross_expected_revenue,gross_amount,form_created_on_closed_opp,market_type,_merge
0,29edde17-6d86-11e8-9f89-0ac7678cb9c1,2018-06-11 10:46:03,masonparrish@iheartmedia.com,PENN FC,AdWire | Radio Ad Ideas + Draft Script,Mason Parrish,"St. Petersburg, FL | Inside Sales",18,MasonP1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,6bd3b41c-6db3-11e8-9f89-0ac7678cb9c1,2018-06-11 16:10:01,samgerb@iheartmedia.com,Banana Beach Tan,AdWire | Radio Ad Ideas + Draft Script,Sam Gerb,"St. Petersburg, FL | Inside Sales",10,SFO-5168157,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,32f41d0e-6db4-11e8-9f89-0ac7678cb9c1,2018-06-11 16:15:35,debracreelman@iheartmedia.com,"Flawless Med Spa: Julie Kalsi Beri, DO",AdWire | Radio Ad Ideas + Draft Script,Debra Creelman,"St. Petersburg, FL | Inside Sales",9,SFO-4883207,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,cb106404-6db4-11e8-9f89-0ac7678cb9c1,2018-06-11 16:19:50,jeffreycroy@iheartmedia.com,Sprague Roofing,AdWire | Radio Ad Ideas + Draft Script,Jeff Croy,"St. Petersburg, FL | Inside Sales",2,PattyRacener1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,ebec1a77-6db4-11e8-9f89-0ac7678cb9c1,2018-06-11 16:20:45,christinasovich@iheartmedia.com,Chicago the Musical,AdWire | Radio Ad Ideas + Draft Script,Christina Sovich,"St. Petersburg, FL | Inside Sales",13,https://ihm.my.,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only